# Generated by Django 5.2.5 on 2025-09-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_app', '0002_task_assigned_to_task_deadline_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
