# Generated by Django 5.2.5 on 2025-09-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_app', '0006_task_assigned_to_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.CharField(max_length=200),
        ),
    ]
