# Generated by Django 5.2.5 on 2025-09-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_app', '0007_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
